import Config

# Track environment at runtime (for conditional behavior in workers, etc.)
config :social_objects, env: :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :social_objects, SocialObjectsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Enable Oban cron jobs in production
config :social_objects, Oban,
  plugins: [
    {Oban.Plugins.Pruner, max_age: 60 * 60 * 24 * 7},
    {Oban.Plugins.Lifeline, rescue_after: :timer.seconds(60)},
    {Oban.Plugins.Cron,
     crontab: [
       # Sync products every 24 hours (at midnight UTC)
       {"0 0 * * *", SocialObjects.Workers.BrandCronWorker, args: %{task: "shopify_sync"}},
       # Sync TikTok Shop products every 24 hours (at midnight UTC)
       {"0 0 * * *", SocialObjects.Workers.BrandCronWorker, args: %{task: "tiktok_sync"}},
       # Sync BigQuery orders to Creator CRM every 24 hours (at midnight UTC)
       {"0 0 * * *", SocialObjects.Workers.BrandCronWorker, args: %{task: "bigquery_sync"}},
       # Refresh TikTok access token every 30 minutes (prevents token expiration)
       {"*/30 * * * *", SocialObjects.Workers.BrandCronWorker,
        args: %{task: "tiktok_token_refresh"}},
       # Monitor TikTok live status every 2 minutes
       {"*/2 * * * *", SocialObjects.Workers.BrandCronWorker,
        args: %{task: "tiktok_live_monitor"}},
       # Enrich creator profiles from TikTok Marketplace API every hour
       # Reduced from 30min due to rate limiting; smaller batches (40) per run
       # 24 runs/day × 40 = 960 creators/day (conservative to avoid rate limits)
       {"0 * * * *", SocialObjects.Workers.BrandCronWorker, args: %{task: "creator_enrichment"}},
       # Sync TikTok Shop Analytics data to streams every 6 hours
       {"0 */6 * * *", SocialObjects.Workers.BrandCronWorker,
        args: %{task: "stream_analytics_sync"}},
       # Sync video performance data daily at 4am UTC
       {"0 4 * * *", SocialObjects.Workers.BrandCronWorker, args: %{task: "video_sync"}},
       # Sync product performance data every 2 days at 5am UTC (after video sync)
       # Reduced from daily due to persistent TikTok API rate limiting
       {"0 5 */2 * *", SocialObjects.Workers.BrandCronWorker,
        args: %{task: "product_performance_sync"}},
       # Sync brand-specific content GMV daily at 6am UTC (after product performance sync)
       {"0 6 * * *", SocialObjects.Workers.BrandCronWorker, args: %{task: "brand_gmv_sync"}},
       # Refresh creator engagement ranks daily at 7am UTC (after brand GMV sync)
       {"0 7 * * *", SocialObjects.Workers.BrandCronWorker,
        args: %{task: "creator_engagement_ranking"}},
       # Weekly stream recap every Monday at 9 AM PST (5 PM UTC)
       # Covers previous week (Mon-Sun) - all streams will be 2+ days old and synced
       {"0 17 * * 1", SocialObjects.Workers.BrandCronWorker,
        args: %{task: "weekly_stream_recap"}},
       # Sync creator sample purchases daily at 3 AM UTC
       {"0 3 * * *", SocialObjects.Workers.BrandCronWorker,
        args: %{task: "creator_purchase_sync"}}
     ]}
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
