import Config

# Track environment at runtime (for conditional behavior in workers, etc.)
config :pavoi, env: :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :pavoi, PavoiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Enable Oban cron jobs in production
config :pavoi, Oban,
  plugins: [
    {Oban.Plugins.Pruner, max_age: 60 * 60 * 24 * 7},
    {Oban.Plugins.Lifeline, rescue_after: :timer.seconds(60)},
    {Oban.Plugins.Cron,
     crontab: [
       # Sync products every 24 hours (at midnight UTC)
       {"0 0 * * *", Pavoi.Workers.BrandCronWorker, args: %{task: "shopify_sync"}},
       # Sync TikTok Shop products every 24 hours (at midnight UTC)
       {"0 0 * * *", Pavoi.Workers.BrandCronWorker, args: %{task: "tiktok_sync"}},
       # Sync BigQuery orders to Creator CRM every 24 hours (at midnight UTC)
       {"0 0 * * *", Pavoi.Workers.BrandCronWorker, args: %{task: "bigquery_sync"}},
       # Refresh TikTok access token every 30 minutes (prevents token expiration)
       {"*/30 * * * *", Pavoi.Workers.BrandCronWorker, args: %{task: "tiktok_token_refresh"}},
       # Monitor TikTok live status every 2 minutes
       {"*/2 * * * *", Pavoi.Workers.BrandCronWorker, args: %{task: "tiktok_live_monitor"}},
       # Enrich creator profiles from TikTok Marketplace API every 30 minutes
       # Small batches (75) complete quickly, avoiding rate limits
       # 48 runs/day × 75 = 3600 creators/day (with margin for rate limit pauses)
       {"*/30 * * * *", Pavoi.Workers.BrandCronWorker, args: %{task: "creator_enrichment"}},
       # Sync TikTok Shop Analytics data to streams every 6 hours
       {"0 */6 * * *", Pavoi.Workers.BrandCronWorker, args: %{task: "stream_analytics_sync"}},
       # Sync video performance data daily at 4am UTC
       {"0 4 * * *", Pavoi.Workers.BrandCronWorker, args: %{task: "video_sync"}},
       # Sync product performance data daily at 5am UTC (after video sync)
       {"0 5 * * *", Pavoi.Workers.BrandCronWorker, args: %{task: "product_performance_sync"}},
       # Weekly stream recap every Friday at 3 PM PST (11 PM UTC)
       {"0 23 * * 5", Pavoi.Workers.BrandCronWorker, args: %{task: "weekly_stream_recap"}}
     ]}
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
